name: Copy Data to Private Repo

on:
  push:
    branches:
      - main

jobs:
  copy-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout public repository
        uses: actions/checkout@v2

      - name: Checkout private repository
        uses: actions/checkout@v2
        with:
          repository: baljeetn/test
          token: ${{ secrets.PRIVATE_REPO_TOKEN }}

      - name: Copy data from public to private repository
        run: |
          cp -r test/main/* dev/main/
          cd test
          git config user.name "baljeet"
          git config user.email "baljeet@gmail.com"

          git add .
          git commit -m "Copy data from public repository"
          git push
