name: Access Private Repo Data

on:
  push:
    branches:
      - main

jobs:
  access-private-repo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout public repository
        uses: actions/checkout@v2

      - name: Checkout private repository
        uses: actions/checkout@v2
        with:
          repository: baljeetn/test
          token: ${{ secrets.PRIVATE_REPO_TOKEN }}

      - name: Copy data from private to public repository
        run: |
          cp -r baljeetn/test/* baljeetn/dev/
          cd dev
          git config user.name "happy"
          git config user.email "happy@gmail.com"

          git add .
          git commit -m "Copy data from private repository"
          git push
