name: Access Private Repo

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout public repo
      uses: actions/checkout@v2

    - name: Checkout private repo
      uses: actions/checkout@v2
      with:
        repository: baljeetn/test
        token: ${{ secrets.PRIVATE_REPO_TOKEN }}

    
    - name: Copy private repo code to public repo
      run: |
          cp -R test/main/* dev/main/
    # Add your desired steps here to work with the code from the private repo
